---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Jellyfin:
    - Jellyfin:
        href: http://j.home.bone6.top/
        description: Jellyfin
        widget:
            type: jellyfin
            url: http://j.home.bone6.top/
            key: a07afbcd7a684dae8543c9ea5c4e1e60
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
    
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://s.home.bone6.top/
        widget:
            type: jellyseerr
            fields: ["pending", "approved", "available"]
            url: http://s.home.bone6.top
            key: MTY3ODc5MjA4OTAyMWYzYzMzZTZkLWViZmYtNDY0Ni1hMmQyLTcxNzU5MTcwNGRhYw
    
    - Radarr:
        icon: radarr.png
        href: http://192.168.2.101:8989
        widget:
            type: radarr
            fileds: ["wanted", "missing", "queued", "movies"]
            url: http://192.168.2.101:8989
            key: 0fbdb6b2b74c4a06b34d4eac87de9fdf

- 下载:
    - qBittorent:
        href: http://192.168.2.101:8081
        description: qBittorent
        widget:
            type: qbittorrent
            url: http://192.168.2.101:8081

