version: "3"
services:
  boning-mlir:
    image: zrr1999/boning-mlir:latest
    container_name: boning
    ports:
      - 10001:22
    restart: unless-stopped
  typst:
    image: zrr1999/typst:latest
    container_name: typst
    ports:
      - 10002:22
    restart: unless-stopped
