version: '2'
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    volumes:
      - ~/workspace/compose-config/qinglong:/ql/data
    ports:
      - 5700:5700
    environment:
      # 部署路径非必须，以斜杠开头和结尾，比如 /test/
      QlBaseUrl: '/'
    restart: unless-stopped
