version: '3.3'

# docker network create -d macvlan --subnet=192.168.2.0/24 --gateway=192.168.2.1 -o parent=eth0.10 macnet
# docker run -d --name=OpenWrt --restart always --privileged --network macnet --ip 192.168.2.5 piaoyizy/openwrt-x86
services:
  openwrt:
    image: piaoyizy/openwrt-x86:latest
    container_name: OpenWrt
    network_mode: macnet
    privileged: true
    restart: always
    ulimits:
      nofile:
        soft: 16384
        hard: 65536
