---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
title: 家庭主页
language: cn-ZH

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
