name: Production Docker Image Build and Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "dockerfiles/prod/*/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "dockerfiles/prod/*/Dockerfile"
jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        image: ["zrr-tools", "caddy", "lobe-chat"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push dev docker image (${{matrix.image}})
        uses: docker/build-push-action@v5
        if: contains(github.event.head_commit.modified, 'zrr-docker/prod/dockerfiles/${{matrix.image}}/Dockerfile')
        with:
          context: ./dockerfiles/prod/${{matrix.image}}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ github.sha}}
      - name: Build and push docker image (${{matrix.image}})
        uses: docker/build-push-action@v5
        if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'zrr-docker/prod/dockerfiles/${{matrix.image}}/Dockerfile')
        with:
          context: ./dockerfiles/prod/${{matrix.image}}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:latest
