name: Docker Image Build and Push

on:
  push:
    branches: [main, develop]
    paths:
      - '**/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push docker base image
      uses: docker/build-push-action@v2
      if: github.event_name == 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/zrr-base
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:${{ env.COMMIT_ID }}
    - name: Build and push docker base image
      uses: docker/build-push-action@v2
      if: github.event_name != 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/zrr-base
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:latest
