name: Docker Image Build and Push

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - '**/Dockerfile'
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push docker base image
      uses: docker/build-push-action@v5
      if: github.event_name == 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/zrr-base
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:${{ env.COMMIT_ID }}
    - name: Build and push docker base image
      uses: docker/build-push-action@v5
      if: github.event_name == 'push'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/zrr-base
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/zrr-base:latest
  build-other-images-needs-base:
    needs: [build-base-image]
    strategy:
      fail-fast: false
      matrix:
        image: ["zrr-main", "zrr-paddle"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image (${{matrix.image}})
      uses: docker/build-push-action@v5
      if: github.event_name == 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ env.COMMIT_ID }}
    - name: Build and push Docker image (${{matrix.image}})
      uses: docker/build-push-action@v5
      if: github.event_name != 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:latest
  build-other-images:
    strategy:
      fail-fast: false
      matrix:
        image: ["zrr-tools"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image (${{matrix.image}})
      uses: docker/build-push-action@v5
      if: github.event_name == 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ env.COMMIT_ID }}
    - name: Build and push Docker image (${{matrix.image}})
      uses: docker/build-push-action@v5
      if: github.event_name != 'pull_request'
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:latest
