name: CodeStyle Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    name: CodeStyle Check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pre-commit>=3.0.0

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
