name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Dockerfile'
jobs:
  build:
    strategy:
      matrix:
        image: ["zrr-base", "zrr-tools"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image (${{matrix.image}})
      uses: docker/build-push-action@v2
      env:
        COMMIT_ID: ${{ github.sha}}
      with:
        context: ./dockerfiles/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:${{ env.COMMIT_ID }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{matrix.image}}:latest
