name: Docker Image Build and Push

on:
  push:
    branches: [ "master" ]
    paths:
      - 'dockers/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'dockers/**'

jobs:
  build:
    strategy:
      matrix:
        image: ["zrr-base", "zrr-tools"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      env:
        COMMIT_ID: ${{ github.sha }}:8
      with:
        context: ./dockers/${{matrix.image}}
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{matrix.image}}:$COMMIT_ID
          ${{ secrets.DOCKER_USERNAME }}/${{matrix.image}}:latest
